[package]
name = "n_body_simulator"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.10"
log = "0.4"
wgpu = "25.0.0"
winit = "0.30.9"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
pollster = "0.4.0"
